name: IntegrationContinue

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Étape 1 : Récupération du code
      - name: Checkout du code
        uses: actions/checkout@v4
      
      # Étape 2 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      # Étape 3 : Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Étape 4 : Exécution des tests
      - name: Tests execution
        run: |
          coverage run -m unittest tests/test_calculator.py
          coverage report -m